version: '3'
services:
  
  geoserver:
    image: 'jemacchi/geoserver:2.16.2'
    hostname: geoserver
    env_file:
      - ./geoserver.env
    ports:
      - '8080:8080'
    depends_on:
      - postgis
    restart: on-failure

  postgis:
    image: 'kartoza/postgis:9.6-2.4'
    hostname: postgis
    env_file:
      - ./postgis.env
    ports:
      - '5432:5432'
    restart: on-failure

