version: '3'

services:
  
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=soporte123
    ports:
      - '80:80'
      
  postgis:
    image: 'kartoza/postgis:9.6-2.4'
    hostname: postgis
    env_file:
      - ./postgis.env
    ports:
      - '5432:5432'
    restart: on-failure
    healthcheck:
      test: exit 0
